// Copyright 2025 ETH Zurich and University of Bologna.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51

// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module slink_reg #(
        parameter ID_WIDTH = 1
    ) (
        input wire clk,
        input wire arst_n,

        input wire s_obi_req,
        output logic s_obi_gnt,
        input wire [11:0] s_obi_addr,
        input wire s_obi_we,
        input wire [3:0] s_obi_be,
        input wire [31:0] s_obi_wdata,
        input wire [ID_WIDTH-1:0] s_obi_aid,
        output logic s_obi_rvalid,
        input wire s_obi_rready,
        output logic [31:0] s_obi_rdata,
        output logic s_obi_err,
        output logic [ID_WIDTH-1:0] s_obi_rid,

        input slink_reg_pkg::slink_reg__in_t hwif_in,
        output slink_reg_pkg::slink_reg__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [11:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // State & holding regs
    logic is_active; // A request is being served (not yet fully responded)
    logic gnt_q; // one-cycle grant for A-channel
    logic rsp_pending; // response ready but not yet accepted by manager
    logic [31:0] rsp_rdata_q;
    logic rsp_err_q;
    logic [$bits(s_obi_rid)-1:0] rid_q;

    // Latch AID on accept to echo back the response
    always_ff @(posedge clk or negedge arst_n) begin
        if (~arst_n) begin
            is_active <= 1'b0;
            gnt_q <= 1'b0;
            rsp_pending <= 1'b0;
            rsp_rdata_q <= '0;
            rsp_err_q <= 1'b0;
            rid_q <= '0;

            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            // defaults
            cpuif_req <= 1'b0;
            gnt_q <= s_obi_req & ~is_active;

            // Accept new request when idle
            if (~is_active) begin
                if (s_obi_req) begin
                    is_active <= 1'b1;
                    cpuif_req <= 1'b1;
                    cpuif_req_is_wr <= s_obi_we;
                    cpuif_addr <= {s_obi_addr[11:2], 2'b0};
                    cpuif_wr_data <= s_obi_wdata;
                    rid_q <= s_obi_aid;
                    for (int i = 0; i < 4; i++) begin
                        cpuif_wr_biten[i*8 +: 8] <= {8{ s_obi_be[i] }};
                    end
                end
            end

            // Capture response
            if (is_active && (cpuif_rd_ack || cpuif_wr_ack)) begin
                rsp_pending <= 1'b1;
                rsp_rdata_q <= cpuif_rd_data;
                rsp_err_q <= cpuif_rd_err | cpuif_wr_err;
                // NOTE: Keep 'is_active' asserted until the external R handshake completes
            end

            // Complete external R-channel handshake only if manager ready
            if (rsp_pending && s_obi_rvalid && s_obi_rready) begin
                rsp_pending <= 1'b0;
                is_active <= 1'b0; // free to accept the next request
            end
        end
    end

    // R-channel outputs (held stable while rsp_pending=1)
    assign s_obi_rvalid = rsp_pending;
    assign s_obi_rdata = rsp_rdata_q;
    assign s_obi_err = rsp_err_q;
    assign s_obi_rid = rid_q;

    // A-channel grant (registered one-cycle pulse when we accept a request)
    assign s_obi_gnt = gnt_q;

    logic cpuif_req_masked;
    logic external_req;
    logic external_pending;
    logic external_wr_ack;
    logic external_rd_ack;
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            external_pending <= '0;
        end else begin
            if(external_req & ~external_wr_ack & ~external_rd_ack) external_pending <= '1;
            else if(external_wr_ack | external_rd_ack) external_pending <= '0;
            `ifndef SYNTHESIS
                assert_bad_ext_wr_ack: assert(!external_wr_ack || (external_pending | external_req))
                    else $error("An external wr_ack strobe was asserted when no external request was active");
                assert_bad_ext_rd_ack: assert(!external_rd_ack || (external_pending | external_req))
                    else $error("An external rd_ack strobe was asserted when no external request was active");
            `endif
        end
    end

    // Read & write latencies are balanced. Stalls not required
    // except if external
    assign cpuif_req_stall_rd = external_pending;
    assign cpuif_req_stall_wr = external_pending;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic ctrl;
        logic error;
        logic node_id;
        logic raw_mode_en;
        logic raw_mode_in_data;
        logic raw_mode_in_ch_sel;
        logic raw_mode_out_data_fifo;
        logic raw_mode_out_data_fifo_ctrl;
        logic raw_mode_out_en;
        logic flow_control_fifo_clear;
        logic raw_mode_in_data_valid[1];
        logic raw_mode_out_ch_mask[1];
        logic tx_phy_clk_div[1];
        logic tx_phy_clk_start[1];
        logic tx_phy_clk_end[1];
        logic channel_alloc_tx_cfg;
        logic channel_alloc_tx_ctrl;
        logic channel_alloc_rx_cfg;
        logic channel_alloc_rx_ctrl;
        logic channel_alloc_tx_ch_en[1];
        logic channel_alloc_rx_ch_en[1];
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic decoded_strb_is_external;

    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_invalid_rw;
        automatic logic is_external;
        is_external = '0;
        is_valid_addr = '1; // No error checking on valid address access
        is_invalid_rw = '0;
        decoded_reg_strb.ctrl = cpuif_req_masked & (cpuif_addr == 12'h0);
        decoded_reg_strb.error = cpuif_req_masked & (cpuif_addr == 12'h4);
        decoded_reg_strb.node_id = cpuif_req_masked & (cpuif_addr == 12'h8);
        decoded_reg_strb.raw_mode_en = cpuif_req_masked & (cpuif_addr == 12'hc) & cpuif_req_is_wr;
        decoded_reg_strb.raw_mode_in_data = cpuif_req_masked & (cpuif_addr == 12'h10) & !cpuif_req_is_wr;
        is_external |= cpuif_req_masked & (cpuif_addr == 12'h10) & !cpuif_req_is_wr;
        decoded_reg_strb.raw_mode_in_ch_sel = cpuif_req_masked & (cpuif_addr == 12'h14) & cpuif_req_is_wr;
        decoded_reg_strb.raw_mode_out_data_fifo = cpuif_req_masked & (cpuif_addr == 12'h18) & cpuif_req_is_wr;
        decoded_reg_strb.raw_mode_out_data_fifo_ctrl = cpuif_req_masked & (cpuif_addr == 12'h1c);
        is_external |= cpuif_req_masked & (cpuif_addr == 12'h1c);
        decoded_reg_strb.raw_mode_out_en = cpuif_req_masked & (cpuif_addr == 12'h20);
        decoded_reg_strb.flow_control_fifo_clear = cpuif_req_masked & (cpuif_addr == 12'h24) & cpuif_req_is_wr;
        is_external |= cpuif_req_masked & (cpuif_addr == 12'h24) & cpuif_req_is_wr;
        for(int i0=0; i0<1; i0++) begin
            decoded_reg_strb.raw_mode_in_data_valid[i0] = cpuif_req_masked & (cpuif_addr == 12'h100 + (12)'(i0) * 12'h4) & !cpuif_req_is_wr;
            is_external |= cpuif_req_masked & (cpuif_addr == 12'h100 + (12)'(i0) * 12'h4) & !cpuif_req_is_wr;
        end
        for(int i0=0; i0<1; i0++) begin
            decoded_reg_strb.raw_mode_out_ch_mask[i0] = cpuif_req_masked & (cpuif_addr == 12'h200 + (12)'(i0) * 12'h4) & cpuif_req_is_wr;
        end
        for(int i0=0; i0<1; i0++) begin
            decoded_reg_strb.tx_phy_clk_div[i0] = cpuif_req_masked & (cpuif_addr == 12'h300 + (12)'(i0) * 12'h4);
        end
        for(int i0=0; i0<1; i0++) begin
            decoded_reg_strb.tx_phy_clk_start[i0] = cpuif_req_masked & (cpuif_addr == 12'h400 + (12)'(i0) * 12'h4);
        end
        for(int i0=0; i0<1; i0++) begin
            decoded_reg_strb.tx_phy_clk_end[i0] = cpuif_req_masked & (cpuif_addr == 12'h500 + (12)'(i0) * 12'h4);
        end
        decoded_reg_strb.channel_alloc_tx_cfg = cpuif_req_masked & (cpuif_addr == 12'h600) & !cpuif_req_is_wr;
        decoded_reg_strb.channel_alloc_tx_ctrl = cpuif_req_masked & (cpuif_addr == 12'h604) & !cpuif_req_is_wr;
        is_external |= cpuif_req_masked & (cpuif_addr == 12'h604) & !cpuif_req_is_wr;
        decoded_reg_strb.channel_alloc_rx_cfg = cpuif_req_masked & (cpuif_addr == 12'h608) & !cpuif_req_is_wr;
        decoded_reg_strb.channel_alloc_rx_ctrl = cpuif_req_masked & (cpuif_addr == 12'h60c) & !cpuif_req_is_wr;
        is_external |= cpuif_req_masked & (cpuif_addr == 12'h60c) & !cpuif_req_is_wr;
        for(int i0=0; i0<1; i0++) begin
            decoded_reg_strb.channel_alloc_tx_ch_en[i0] = cpuif_req_masked & (cpuif_addr == 12'h700 + (12)'(i0) * 12'h4) & !cpuif_req_is_wr;
        end
        for(int i0=0; i0<1; i0++) begin
            decoded_reg_strb.channel_alloc_rx_ch_en[i0] = cpuif_req_masked & (cpuif_addr == 12'h800 + (12)'(i0) * 12'h4) & !cpuif_req_is_wr;
        end
        decoded_err = (~is_valid_addr | is_invalid_rw) & decoded_req;
        decoded_strb_is_external = is_external;
        external_req = is_external;
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic next;
                logic load_next;
            } stop_send;
        } ctrl;
        struct {
            struct {
                logic next;
                logic load_next;
            } looped_rsp;
        } error;
        struct {
            struct {
                logic [3:0] next;
                logic load_next;
            } node_id;
        } node_id;
        struct {
            struct {
                logic next;
                logic load_next;
            } raw_mode_en;
        } raw_mode_en;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } raw_mode_in_ch_sel;
        } raw_mode_in_ch_sel;
        struct {
            struct {
                logic [15:0] next;
                logic load_next;
            } raw_mode_out_data_fifo;
        } raw_mode_out_data_fifo;
        struct {
            struct {
                logic next;
                logic load_next;
            } raw_mode_out_en;
        } raw_mode_out_en;
        struct {
            struct {
                logic next;
                logic load_next;
            } raw_mode_out_ch_mask;
        } raw_mode_out_ch_mask[1];
        struct {
            struct {
                logic [10:0] next;
                logic load_next;
            } clk_divs;
        } tx_phy_clk_div[1];
        struct {
            struct {
                logic [10:0] next;
                logic load_next;
            } clk_divs;
        } tx_phy_clk_start[1];
        struct {
            struct {
                logic [10:0] next;
                logic load_next;
            } clk_shift_end;
        } tx_phy_clk_end[1];
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic value;
            } stop_send;
        } ctrl;
        struct {
            struct {
                logic value;
            } looped_rsp;
        } error;
        struct {
            struct {
                logic [3:0] value;
            } node_id;
        } node_id;
        struct {
            struct {
                logic value;
            } raw_mode_en;
        } raw_mode_en;
        struct {
            struct {
                logic [7:0] value;
            } raw_mode_in_ch_sel;
        } raw_mode_in_ch_sel;
        struct {
            struct {
                logic [15:0] value;
            } raw_mode_out_data_fifo;
        } raw_mode_out_data_fifo;
        struct {
            struct {
                logic value;
            } raw_mode_out_en;
        } raw_mode_out_en;
        struct {
            struct {
                logic value;
            } raw_mode_out_ch_mask;
        } raw_mode_out_ch_mask[1];
        struct {
            struct {
                logic [10:0] value;
            } clk_divs;
        } tx_phy_clk_div[1];
        struct {
            struct {
                logic [10:0] value;
            } clk_divs;
        } tx_phy_clk_start[1];
        struct {
            struct {
                logic [10:0] value;
            } clk_shift_end;
        } tx_phy_clk_end[1];
    } field_storage_t;
    field_storage_t field_storage;

    // Field: slink_reg.ctrl.stop_send
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.ctrl.stop_send.value;
        load_next_c = '0;
        if(decoded_reg_strb.ctrl && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.ctrl.stop_send.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.ctrl.stop_send.next = next_c;
        field_combo.ctrl.stop_send.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.ctrl.stop_send.value <= 1'h0;
        end else begin
            if(field_combo.ctrl.stop_send.load_next) begin
                field_storage.ctrl.stop_send.value <= field_combo.ctrl.stop_send.next;
            end
        end
    end
    assign hwif_out.ctrl.stop_send.value = field_storage.ctrl.stop_send.value;
    // Field: slink_reg.error.looped_rsp
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.error.looped_rsp.value;
        load_next_c = '0;
        if(decoded_reg_strb.error && decoded_req_is_wr) begin // SW write 1 clear
            next_c = field_storage.error.looped_rsp.value & ~(decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.error.looped_rsp.next;
            load_next_c = '1;
        end
        field_combo.error.looped_rsp.next = next_c;
        field_combo.error.looped_rsp.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.error.looped_rsp.value <= 1'h0;
        end else begin
            if(field_combo.error.looped_rsp.load_next) begin
                field_storage.error.looped_rsp.value <= field_combo.error.looped_rsp.next;
            end
        end
    end
    // Field: slink_reg.node_id.node_id
    always_comb begin
        automatic logic [3:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.node_id.node_id.value;
        load_next_c = '0;
        if(decoded_reg_strb.node_id && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.node_id.node_id.value & ~decoded_wr_biten[3:0]) | (decoded_wr_data[3:0] & decoded_wr_biten[3:0]);
            load_next_c = '1;
        end
        field_combo.node_id.node_id.next = next_c;
        field_combo.node_id.node_id.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.node_id.node_id.value <= 4'h0;
        end else begin
            if(field_combo.node_id.node_id.load_next) begin
                field_storage.node_id.node_id.value <= field_combo.node_id.node_id.next;
            end
        end
    end
    assign hwif_out.node_id.node_id.value = field_storage.node_id.node_id.value;
    // Field: slink_reg.raw_mode_en.raw_mode_en
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.raw_mode_en.raw_mode_en.value;
        load_next_c = '0;
        if(decoded_reg_strb.raw_mode_en && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.raw_mode_en.raw_mode_en.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.raw_mode_en.raw_mode_en.next = next_c;
        field_combo.raw_mode_en.raw_mode_en.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.raw_mode_en.raw_mode_en.value <= 1'h0;
        end else begin
            if(field_combo.raw_mode_en.raw_mode_en.load_next) begin
                field_storage.raw_mode_en.raw_mode_en.value <= field_combo.raw_mode_en.raw_mode_en.next;
            end
        end
    end
    assign hwif_out.raw_mode_en.raw_mode_en.value = field_storage.raw_mode_en.raw_mode_en.value;
    // External register: slink_reg.raw_mode_in_data

    assign hwif_out.raw_mode_in_data.req = !decoded_req_is_wr ? decoded_reg_strb.raw_mode_in_data : '0;
    assign hwif_out.raw_mode_in_data.req_is_wr = decoded_req_is_wr;
    // Field: slink_reg.raw_mode_in_ch_sel.raw_mode_in_ch_sel
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.raw_mode_in_ch_sel.raw_mode_in_ch_sel.value;
        load_next_c = '0;
        if(decoded_reg_strb.raw_mode_in_ch_sel && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.raw_mode_in_ch_sel.raw_mode_in_ch_sel.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.raw_mode_in_ch_sel.raw_mode_in_ch_sel.next = next_c;
        field_combo.raw_mode_in_ch_sel.raw_mode_in_ch_sel.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.raw_mode_in_ch_sel.raw_mode_in_ch_sel.value <= 8'h0;
        end else begin
            if(field_combo.raw_mode_in_ch_sel.raw_mode_in_ch_sel.load_next) begin
                field_storage.raw_mode_in_ch_sel.raw_mode_in_ch_sel.value <= field_combo.raw_mode_in_ch_sel.raw_mode_in_ch_sel.next;
            end
        end
    end
    assign hwif_out.raw_mode_in_ch_sel.raw_mode_in_ch_sel.value = field_storage.raw_mode_in_ch_sel.raw_mode_in_ch_sel.value;
    // Field: slink_reg.raw_mode_out_data_fifo.raw_mode_out_data_fifo
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.raw_mode_out_data_fifo.raw_mode_out_data_fifo.value;
        load_next_c = '0;
        if(decoded_reg_strb.raw_mode_out_data_fifo && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.raw_mode_out_data_fifo.raw_mode_out_data_fifo.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.raw_mode_out_data_fifo.raw_mode_out_data_fifo.next = next_c;
        field_combo.raw_mode_out_data_fifo.raw_mode_out_data_fifo.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.raw_mode_out_data_fifo.raw_mode_out_data_fifo.value <= 16'h0;
        end else begin
            if(field_combo.raw_mode_out_data_fifo.raw_mode_out_data_fifo.load_next) begin
                field_storage.raw_mode_out_data_fifo.raw_mode_out_data_fifo.value <= field_combo.raw_mode_out_data_fifo.raw_mode_out_data_fifo.next;
            end
        end
    end
    assign hwif_out.raw_mode_out_data_fifo.raw_mode_out_data_fifo.value = field_storage.raw_mode_out_data_fifo.raw_mode_out_data_fifo.value;
    assign hwif_out.raw_mode_out_data_fifo.raw_mode_out_data_fifo.swmod = decoded_reg_strb.raw_mode_out_data_fifo && decoded_req_is_wr && |(decoded_wr_biten[15:0]);
    // External register: slink_reg.raw_mode_out_data_fifo_ctrl
    assign hwif_out.raw_mode_out_data_fifo_ctrl.req = decoded_reg_strb.raw_mode_out_data_fifo_ctrl;
    assign hwif_out.raw_mode_out_data_fifo_ctrl.req_is_wr = decoded_req_is_wr;
    assign hwif_out.raw_mode_out_data_fifo_ctrl.wr_data = decoded_wr_data;
    assign hwif_out.raw_mode_out_data_fifo_ctrl.wr_biten = decoded_wr_biten;
    // Field: slink_reg.raw_mode_out_en.raw_mode_out_en
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.raw_mode_out_en.raw_mode_out_en.value;
        load_next_c = '0;
        if(decoded_reg_strb.raw_mode_out_en && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.raw_mode_out_en.raw_mode_out_en.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.raw_mode_out_en.raw_mode_out_en.next = next_c;
        field_combo.raw_mode_out_en.raw_mode_out_en.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.raw_mode_out_en.raw_mode_out_en.value <= 1'h0;
        end else begin
            if(field_combo.raw_mode_out_en.raw_mode_out_en.load_next) begin
                field_storage.raw_mode_out_en.raw_mode_out_en.value <= field_combo.raw_mode_out_en.raw_mode_out_en.next;
            end
        end
    end
    assign hwif_out.raw_mode_out_en.raw_mode_out_en.value = field_storage.raw_mode_out_en.raw_mode_out_en.value;
    // External register: slink_reg.flow_control_fifo_clear

    assign hwif_out.flow_control_fifo_clear.req = decoded_req_is_wr ? decoded_reg_strb.flow_control_fifo_clear : '0;
    assign hwif_out.flow_control_fifo_clear.req_is_wr = decoded_req_is_wr;
    assign hwif_out.flow_control_fifo_clear.wr_data = decoded_wr_data;
    assign hwif_out.flow_control_fifo_clear.wr_biten = decoded_wr_biten;
    for(genvar i0=0; i0<1; i0++) begin
        // External register: slink_reg.raw_mode_in_data_valid[]

        assign hwif_out.raw_mode_in_data_valid[i0].req = !decoded_req_is_wr ? decoded_reg_strb.raw_mode_in_data_valid[i0] : '0;
        assign hwif_out.raw_mode_in_data_valid[i0].req_is_wr = decoded_req_is_wr;
    end
    for(genvar i0=0; i0<1; i0++) begin
        // Field: slink_reg.raw_mode_out_ch_mask[].raw_mode_out_ch_mask
        always_comb begin
            automatic logic [0:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.raw_mode_out_ch_mask[i0].raw_mode_out_ch_mask.value;
            load_next_c = '0;
            if(decoded_reg_strb.raw_mode_out_ch_mask[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.raw_mode_out_ch_mask[i0].raw_mode_out_ch_mask.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
                load_next_c = '1;
            end
            field_combo.raw_mode_out_ch_mask[i0].raw_mode_out_ch_mask.next = next_c;
            field_combo.raw_mode_out_ch_mask[i0].raw_mode_out_ch_mask.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.raw_mode_out_ch_mask[i0].raw_mode_out_ch_mask.value <= 1'h0;
            end else begin
                if(field_combo.raw_mode_out_ch_mask[i0].raw_mode_out_ch_mask.load_next) begin
                    field_storage.raw_mode_out_ch_mask[i0].raw_mode_out_ch_mask.value <= field_combo.raw_mode_out_ch_mask[i0].raw_mode_out_ch_mask.next;
                end
            end
        end
        assign hwif_out.raw_mode_out_ch_mask[i0].raw_mode_out_ch_mask.value = field_storage.raw_mode_out_ch_mask[i0].raw_mode_out_ch_mask.value;
    end
    for(genvar i0=0; i0<1; i0++) begin
        // Field: slink_reg.tx_phy_clk_div[].clk_divs
        always_comb begin
            automatic logic [10:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.tx_phy_clk_div[i0].clk_divs.value;
            load_next_c = '0;
            if(decoded_reg_strb.tx_phy_clk_div[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.tx_phy_clk_div[i0].clk_divs.value & ~decoded_wr_biten[10:0]) | (decoded_wr_data[10:0] & decoded_wr_biten[10:0]);
                load_next_c = '1;
            end
            field_combo.tx_phy_clk_div[i0].clk_divs.next = next_c;
            field_combo.tx_phy_clk_div[i0].clk_divs.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.tx_phy_clk_div[i0].clk_divs.value <= 11'h8;
            end else begin
                if(field_combo.tx_phy_clk_div[i0].clk_divs.load_next) begin
                    field_storage.tx_phy_clk_div[i0].clk_divs.value <= field_combo.tx_phy_clk_div[i0].clk_divs.next;
                end
            end
        end
        assign hwif_out.tx_phy_clk_div[i0].clk_divs.value = field_storage.tx_phy_clk_div[i0].clk_divs.value;
    end
    for(genvar i0=0; i0<1; i0++) begin
        // Field: slink_reg.tx_phy_clk_start[].clk_divs
        always_comb begin
            automatic logic [10:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.tx_phy_clk_start[i0].clk_divs.value;
            load_next_c = '0;
            if(decoded_reg_strb.tx_phy_clk_start[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.tx_phy_clk_start[i0].clk_divs.value & ~decoded_wr_biten[10:0]) | (decoded_wr_data[10:0] & decoded_wr_biten[10:0]);
                load_next_c = '1;
            end
            field_combo.tx_phy_clk_start[i0].clk_divs.next = next_c;
            field_combo.tx_phy_clk_start[i0].clk_divs.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.tx_phy_clk_start[i0].clk_divs.value <= 11'h2;
            end else begin
                if(field_combo.tx_phy_clk_start[i0].clk_divs.load_next) begin
                    field_storage.tx_phy_clk_start[i0].clk_divs.value <= field_combo.tx_phy_clk_start[i0].clk_divs.next;
                end
            end
        end
        assign hwif_out.tx_phy_clk_start[i0].clk_divs.value = field_storage.tx_phy_clk_start[i0].clk_divs.value;
    end
    for(genvar i0=0; i0<1; i0++) begin
        // Field: slink_reg.tx_phy_clk_end[].clk_shift_end
        always_comb begin
            automatic logic [10:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.tx_phy_clk_end[i0].clk_shift_end.value;
            load_next_c = '0;
            if(decoded_reg_strb.tx_phy_clk_end[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.tx_phy_clk_end[i0].clk_shift_end.value & ~decoded_wr_biten[10:0]) | (decoded_wr_data[10:0] & decoded_wr_biten[10:0]);
                load_next_c = '1;
            end
            field_combo.tx_phy_clk_end[i0].clk_shift_end.next = next_c;
            field_combo.tx_phy_clk_end[i0].clk_shift_end.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.tx_phy_clk_end[i0].clk_shift_end.value <= 11'h6;
            end else begin
                if(field_combo.tx_phy_clk_end[i0].clk_shift_end.load_next) begin
                    field_storage.tx_phy_clk_end[i0].clk_shift_end.value <= field_combo.tx_phy_clk_end[i0].clk_shift_end.next;
                end
            end
        end
        assign hwif_out.tx_phy_clk_end[i0].clk_shift_end.value = field_storage.tx_phy_clk_end[i0].clk_shift_end.value;
    end
    assign hwif_out.channel_alloc_tx_cfg.bypass_en.value = 1'h1;
    assign hwif_out.channel_alloc_tx_cfg.auto_flush_en.value = 1'h1;
    assign hwif_out.channel_alloc_tx_cfg.auto_flush_count.value = 8'h2;
    // External register: slink_reg.channel_alloc_tx_ctrl

    assign hwif_out.channel_alloc_tx_ctrl.req = !decoded_req_is_wr ? decoded_reg_strb.channel_alloc_tx_ctrl : '0;
    assign hwif_out.channel_alloc_tx_ctrl.req_is_wr = decoded_req_is_wr;
    assign hwif_out.channel_alloc_rx_cfg.bypass_en.value = 1'h1;
    assign hwif_out.channel_alloc_rx_cfg.auto_flush_en.value = 1'h1;
    assign hwif_out.channel_alloc_rx_cfg.auto_flush_count.value = 8'h2;
    assign hwif_out.channel_alloc_rx_cfg.sync_en.value = 1'h1;
    // External register: slink_reg.channel_alloc_rx_ctrl

    assign hwif_out.channel_alloc_rx_ctrl.req = !decoded_req_is_wr ? decoded_reg_strb.channel_alloc_rx_ctrl : '0;
    assign hwif_out.channel_alloc_rx_ctrl.req_is_wr = decoded_req_is_wr;
    for(genvar i0=0; i0<1; i0++) begin
        assign hwif_out.channel_alloc_tx_ch_en[i0].channel_alloc_tx_ch_en.value = 1'h1;
    end
    for(genvar i0=0; i0<1; i0++) begin
        assign hwif_out.channel_alloc_rx_ch_en[i0].channel_alloc_rx_ch_en.value = 1'h1;
    end

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    always_comb begin
        automatic logic wr_ack;
        wr_ack = '0;
        wr_ack |= hwif_in.raw_mode_out_data_fifo_ctrl.wr_ack;
        wr_ack |= hwif_in.flow_control_fifo_clear.wr_ack;
        external_wr_ack = wr_ack;
    end
    assign cpuif_wr_ack = external_wr_ack | (decoded_req & decoded_req_is_wr & ~decoded_strb_is_external);
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------
    logic readback_external_rd_ack_c;
    always_comb begin
        automatic logic rd_ack;
        rd_ack = '0;
        rd_ack |= hwif_in.raw_mode_in_data.rd_ack;
        rd_ack |= hwif_in.raw_mode_out_data_fifo_ctrl.rd_ack;
        for(int i0=0; i0<1; i0++) begin
            rd_ack |= hwif_in.raw_mode_in_data_valid[i0].rd_ack;
        end
        rd_ack |= hwif_in.channel_alloc_tx_ctrl.rd_ack;
        rd_ack |= hwif_in.channel_alloc_rx_ctrl.rd_ack;
        readback_external_rd_ack_c = rd_ack;
    end

    logic readback_external_rd_ack;

    assign readback_external_rd_ack = readback_external_rd_ack_c;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[16];
    assign readback_array[0][0:0] = (decoded_reg_strb.ctrl && !decoded_req_is_wr) ? field_storage.ctrl.stop_send.value : '0;
    assign readback_array[0][31:1] = '0;
    assign readback_array[1][0:0] = (decoded_reg_strb.error && !decoded_req_is_wr) ? field_storage.error.looped_rsp.value : '0;
    assign readback_array[1][31:1] = '0;
    assign readback_array[2][3:0] = (decoded_reg_strb.node_id && !decoded_req_is_wr) ? field_storage.node_id.node_id.value : '0;
    assign readback_array[2][31:4] = '0;
    assign readback_array[3] = hwif_in.raw_mode_in_data.rd_ack ? hwif_in.raw_mode_in_data.rd_data : '0;
    assign readback_array[4] = hwif_in.raw_mode_out_data_fifo_ctrl.rd_ack ? hwif_in.raw_mode_out_data_fifo_ctrl.rd_data : '0;
    assign readback_array[5][0:0] = (decoded_reg_strb.raw_mode_out_en && !decoded_req_is_wr) ? field_storage.raw_mode_out_en.raw_mode_out_en.value : '0;
    assign readback_array[5][31:1] = '0;
    for(genvar i0=0; i0<1; i0++) begin
        assign readback_array[i0 * 1 + 6] = hwif_in.raw_mode_in_data_valid[i0].rd_ack ? hwif_in.raw_mode_in_data_valid[i0].rd_data : '0;
    end
    for(genvar i0=0; i0<1; i0++) begin
        assign readback_array[i0 * 1 + 7][10:0] = (decoded_reg_strb.tx_phy_clk_div[i0] && !decoded_req_is_wr) ? field_storage.tx_phy_clk_div[i0].clk_divs.value : '0;
        assign readback_array[i0 * 1 + 7][31:11] = '0;
    end
    for(genvar i0=0; i0<1; i0++) begin
        assign readback_array[i0 * 1 + 8][10:0] = (decoded_reg_strb.tx_phy_clk_start[i0] && !decoded_req_is_wr) ? field_storage.tx_phy_clk_start[i0].clk_divs.value : '0;
        assign readback_array[i0 * 1 + 8][31:11] = '0;
    end
    for(genvar i0=0; i0<1; i0++) begin
        assign readback_array[i0 * 1 + 9][10:0] = (decoded_reg_strb.tx_phy_clk_end[i0] && !decoded_req_is_wr) ? field_storage.tx_phy_clk_end[i0].clk_shift_end.value : '0;
        assign readback_array[i0 * 1 + 9][31:11] = '0;
    end
    assign readback_array[10][0:0] = (decoded_reg_strb.channel_alloc_tx_cfg && !decoded_req_is_wr) ? 1'h1 : '0;
    assign readback_array[10][1:1] = (decoded_reg_strb.channel_alloc_tx_cfg && !decoded_req_is_wr) ? 1'h1 : '0;
    assign readback_array[10][7:2] = '0;
    assign readback_array[10][15:8] = (decoded_reg_strb.channel_alloc_tx_cfg && !decoded_req_is_wr) ? 8'h2 : '0;
    assign readback_array[10][31:16] = '0;
    assign readback_array[11] = hwif_in.channel_alloc_tx_ctrl.rd_ack ? hwif_in.channel_alloc_tx_ctrl.rd_data : '0;
    assign readback_array[12][0:0] = (decoded_reg_strb.channel_alloc_rx_cfg && !decoded_req_is_wr) ? 1'h1 : '0;
    assign readback_array[12][1:1] = (decoded_reg_strb.channel_alloc_rx_cfg && !decoded_req_is_wr) ? 1'h1 : '0;
    assign readback_array[12][7:2] = '0;
    assign readback_array[12][15:8] = (decoded_reg_strb.channel_alloc_rx_cfg && !decoded_req_is_wr) ? 8'h2 : '0;
    assign readback_array[12][16:16] = (decoded_reg_strb.channel_alloc_rx_cfg && !decoded_req_is_wr) ? 1'h1 : '0;
    assign readback_array[12][31:17] = '0;
    assign readback_array[13] = hwif_in.channel_alloc_rx_ctrl.rd_ack ? hwif_in.channel_alloc_rx_ctrl.rd_data : '0;
    for(genvar i0=0; i0<1; i0++) begin
        assign readback_array[i0 * 1 + 14][0:0] = (decoded_reg_strb.channel_alloc_tx_ch_en[i0] && !decoded_req_is_wr) ? 1'h1 : '0;
        assign readback_array[i0 * 1 + 14][31:1] = '0;
    end
    for(genvar i0=0; i0<1; i0++) begin
        assign readback_array[i0 * 1 + 15][0:0] = (decoded_reg_strb.channel_alloc_rx_ch_en[i0] && !decoded_req_is_wr) ? 1'h1 : '0;
        assign readback_array[i0 * 1 + 15][31:1] = '0;
    end

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr & ~decoded_strb_is_external;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<16; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign external_rd_ack = readback_external_rd_ack;
    assign cpuif_rd_ack = readback_done | readback_external_rd_ack;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
